golf_scores/accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views as accounts_views

app_name='accounts'
urlpatterns = [
    path('signup/', accounts_views.signup, name='signup'),
    path('logout/', accounts_views.logout_view, name='logout'),
    path('signin/', accounts_views.signin, name='signin'),
    path('account_management/', accounts_views.account_management, name='account_management'),
    path('change_password/', accounts_views.change_password, name='change_password'),
]

golf_scores/golf_scores/urls.py
from django.contrib import admin
from django.urls import path
from web import views as web_views
from accounts import views as accounts_views

urlpatterns = [
    path('', web_views.index),
    path('home/', web_views.home),
    path('signup/', accounts_views.signup, name='signup'),
    path('logout/', accounts_views.logout_view, name='logout'),
    path('golf_courses/', web_views.golf_courses, name='golf_courses'),
    path('delete_course/', web_views.delete_course, name='delete_course'),
    path('scores/', web_views.scores_view, name='scores'),
    path('delete_score/', web_views.delete_score, name='delete_score'),
    path('signin/', accounts_views.signin, name='signin'),
    path('admin/', admin.site.urls),
]

golf_scores/web/urls.py
from django.contrib import admin
from django.urls import path, include
from web import views as web_views

app_name='web'
urlpatterns = [
    path('', web_views.index, name='index'),
    path('golf_courses/', web_views.golf_courses, name='golf_courses'),
    path('delete_course/', web_views.delete_course, name='delete_course'),
    path('scores/', web_views.scores, name='scores'),
    path('delete_score/', web_views.delete_score, name='delete_score'),
]

golf_scores/accounts/models.py
from django.db import models

golf_scores/web/models.py
from django.db import models
from django.contrib.auth.models import User


class GolfCourse(models.Model):
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    par = models.IntegerField()

    def __str__(self):
        return self.name


class Score(models.Model):
    date = models.DateField()
    golf_course = models.ForeignKey(
        GolfCourse, on_delete=models.CASCADE, related_name='golf_course', default=None)
    score = models.IntegerField()
    to_par = models.IntegerField(editable=False)
    user_score = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user_score', default=None)

    def __str__(self):
        return f'{self.date} - {self.golf_course} - {self.score}'

golf_scores/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest
from django.contrib.auth.models import User
from django.contrib.auth import login, logout
from commons.success_messages import SuccessMessage
from commons.error_messages import ErrorMessage
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required


def signup(request):
    if request.method == 'POST':
        form = request.POST
        if User.objects.filter(username=form.__getitem__('username')).exists():
            return render(request, 'signup.html', {'error_message': ErrorMessage.USERNAME_ALREADY_EXISTS.value})
        if User.objects.filter(email=form.__getitem__('email')).exists():
            return render(request, 'signup.html', {'error_message': ErrorMessage.EMAIL_ALREADY_EXISTS.value})
        if form.__getitem__('password') != form.__getitem__('confirm_password'):
            return render(request, 'signup.html', {'error_message': ErrorMessage.PASSWORDS_DONT_MATCH.value})
        user = User.objects.create_user(form.__getitem__(
            'username'), form.__getitem__('email'), form.__getitem__('password'))
        user.save()
        return render(request, 'signup.html', {'success_message': SuccessMessage.ACCOUNT_CREATED.value})
    if request.method == 'GET':
        return render(request, 'signup.html')


def signin(request):
    if request.method == 'POST':
        form = request.POST
        try:
            user = User.objects.get(username=form.__getitem__('username'))
            if user is not None and user.check_password(form.__getitem__('password')):
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'signin.html', {'error_message': ErrorMessage.USERNAME_OR_PASSWORD_INCORRECT.value})
        except ObjectDoesNotExist:
            return render(request, 'signin.html', {'error_message': ErrorMessage.USERNAME_OR_PASSWORD_INCORRECT.value})
    return render(request, 'signin.html')


@login_required
def logout_view(request):
    logout(request)
    return redirect('/')


@login_required
def account_management(request):
    return render(request, 'account_management.html')


@login_required
def change_password(request):
    if request.user.check_password(request.POST['current-password']) and request.POST['new-password'] == request.POST['confirm-new-password']:
        request.user.set_password(request.POST['new-password'])
        request.user.save()
        login(request, request.user)
        return render(request, 'account_management.html', {'success_message': SuccessMessage.PASSWORD_CHANGED.value})
    elif request.POST['new-password'] != request.POST['confirm-new-password']:
        return render(request, 'account_management.html', {'error_message': ErrorMessage.PASSWORDS_DONT_MATCH.value})
    else:
        return render(request, 'account_management.html', {'error_message': ErrorMessage.WRONG_CURRENT_PASSWORD.value})

golf_scores/web/views.py
from django.shortcuts import render, redirect
from .models import GolfCourse, Score
from commons.error_messages import ErrorMessage
from .helpers import calculate_score_to_par, format_date
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'index.html')

@login_required
def home_view(request):
    return render(request, 'home.html')

@login_required
def golf_courses(request):
    golf_courses = GolfCourse.objects.all().order_by('country')
    if request.method == 'POST':
        if GolfCourse.objects.filter(name=request.POST['name']).exists():
            return render(request, 'golf_courses.html', {'golf_courses': golf_courses, 'error_message': ErrorMessage.COURSE_ALREADY_EXISTS.value})
        golf_course = GolfCourse.objects.create(name=request.POST['name'], city=request.POST[
            'city'], country=request.POST['country'], par=request.POST['par']).save()
        return redirect('/golf_courses')
    return render(request, 'golf_courses.html', {'golf_courses': enumerate(golf_courses, start=1)})

@login_required
def delete_course(request):
    if request.method == 'POST':
        GolfCourse.objects.get(pk=request.POST['id']).delete()
        return redirect('/golf_courses')

@login_required
def scores(request):
    scores = Score.objects.filter(user_score_id=request.user.id).order_by('date').reverse()
    golf_courses = GolfCourse.objects.all()
    if request.method == 'POST':
        golf_course = GolfCourse.objects.filter(
            name=request.POST['golf_course']).first()
        to_par = calculate_score_to_par(int(request.POST['score']), golf_course.par)
        score = Score.objects.create(date=format_date(request.POST[
            'datepicker']), golf_course=golf_course, score=request.POST['score'], to_par=to_par, user_score_id=request.user.id).save()
    return render(request, 'scores.html', {'golf_courses': golf_courses, 'scores': enumerate(scores, start=1)})

@login_required
def delete_score(request):
    if request.method == 'POST':
        Score.objects.get(pk=request.POST['id']).delete()
        return redirect('/scores')

golf_scores/templates/account_management.html
{% extends 'base.html' %} {% block content %}
<div class="centered-container container">
    <div class="sign-form card">
        <form class="form-submit" action="{% url 'accounts:change_password' %}" method="post">
            {% csrf_token %}
            <h3>Account Management</h3>
            <div class="form-group">
                <label for="current-password">Current password</label>
                <input type="password" class="form-control" name="current-password" id="current-password"
                    placeholder="Enter current password">
            </div>
            <div class="form-group">
                <label for="new-password">New password</label>
                <input type="password" class="form-control" name="new-password" id="new-password" placeholder="Enter new password">
            </div>
            <div class="form-group">
                <label for="confirm-new-password">Confirm new password</label>
                <input type="password" class="form-control" name="confirm-new-password" id="confirm-new-password" placeholder="Confirm new pasword">
            </div>
            {% if error_message %}
            <div class="alert alert-danger" role="alert">
                {{ error_message }}
            </div>
            {% elif success_message %}
            <div class="alert alert-info" role="info">
                {{ success_message }}
            </div>
            {% endif %}
            <button type="submit" class="btn btn-lg btn-primary btn-block">Change password</button>
        </form>
    </div>
</div>
{% endblock %}

golf_scores/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- FontAwesome CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
        integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!-- Datepicker CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">
    <!-- CSS -->
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    {% load static %}
    <a class="navbar-brand" href="{% url 'web:index' %}"><img class="logo" src="{% static 'flag.svg' %}">Golf Scores</a> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{% url 'web:index' %}">Home</a>
            {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'web:golf_courses' %}"><i class="fas fa-golf-ball"></i> Golf Courses</a>
            <a class="nav-item nav-link" href="{% url 'web:scores' %}"><i class="fas fa-medal"></i> Scores</a>
            <a class="nav-item nav-link" href="{% url 'accounts:account_management' %}"><i class="fas fa-user"></i> {{ user.username }}</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:signin' %}">Sign In</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
            {% endif %}
        </div>
    </div>
</nav>

<body>
    {% block content %}{% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
    integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
    integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>
{% load static %}
<script src="{% static 'datepicker.js' %}"></script>

</html>

golf_scores/templates/golf_courses.html
{% extends "base.html"%} {% block content %}
<div class="container centered-container">
    <form class="form-submit" action="{% url 'web:golf_courses' %}" method="post">
        {% csrf_token %}
        <h3 class="title">Golf Courses</h3>
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="name" id="name" placeholder="Enter name" required
                title="Name of golf course required">
            <input type="text" class="form-control" name="city" id="city" placeholder="Enter city">
            <input type="text" class="form-control" name="country" id="country" placeholder="Enter country">
            <input type="number" min="0" class="form-control" name="par" id="par" placeholder="Enter Par" required
                title="Golf course par required">
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </div>
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
        {% endif %}
    </form>
    <div class="table table-container">
        <table class="table">
            <thead class="table-primary">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Par</th>
                    <th scope="col">City</th>
                    <th scope="col">Country</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for count, golf_course in golf_courses %}
                <tr>
                    <form action="{% url 'web:delete_course' %}" method="post">
                        {% csrf_token %}
                        <td>{{ count }}</td>
                        <td>{{ golf_course.name }}</td>
                        <td>{{ golf_course.par }}</td>
                        <td>{{ golf_course.city }}</td>
                        <td>{{ golf_course.country }}</td>
                        <td>
                            <button type="submit" class="close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                <input type="hidden" name="id" value="{{ golf_course.id}}">
                            </button>
                        </td>
                    </form>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        {% endblock %}
    </div>

golf_scores/templates/index.html
{% extends 'base.html' %} {% block content %}
{% if user.is_authenticated %}
<div class="container">
    <h1 class="title">Golf Scores</h1>
</div>
<div class="container centered-container">
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Add golf courses</h5>
                    {% load static %}
                    <img src="{% static 'golf_course.svg' %}" class="card-image">
                    <p class="card-text">Here you can add golf courses with other Users</p>
                    <a href="{% url 'web:golf_courses' %}" class="btn btn-primary">Go</a>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Add scores</h5>
                    {% load static %}
                    <img src="{% static 'golf_club.svg' %}" class="card-image">
                    <p class="card-text">Here you can save your own golf scores</p>
                    <a href="{% url 'web:scores' %}" class="btn btn-primary">Go</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <h1 class="title">Golf Scores</h1>
</div>
<div class="container centered-container">
    <div class="card-group">
        <div class="card">
            {% load static %}
            <img class="card-img-top" src="{% static 'Rory.jpeg' %}" alt="Rory McIlroy">
            <div class="card-body">
                <h5 class="card-title">Save your scores</h5>
                <p class="card-text">This website allows you to save your golf scores on courses you've played.</p>
            </div>
        </div>
        <div class="card">
            {% load static %}
            <img class="card-img-top" src="{% static 'Augusta.jpeg' %}" alt="Augusta course">
            <div class="card-body">
                <h5 class="card-title">Golf Courses</h5>
                <p class="card-text">Add golf courses you've played. See golf courses posted by other users.</p>
            </div>
        </div>
        <div class="card">
            {% load static %}
            <img class="card-img-top" src="{% static 'Rory_players.jpeg' %}" alt="Rory with Players trophy">
            <div class="card-body">
                <h5 class="card-title">Manage your scores</h5>
                <p class="card-text">This site allows you to create and delete your golf scores.</p>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

golf_scores/templates/scores.html
{% extends "base.html"%} {% block content %}
<div class="container centered-container">
    <form class="form-submit" action="{% url 'web:scores' %}" method="post">
        {% csrf_token %}
        <h3 class="title">Scores</h3>
        <div class="input-group mb-3">
            <input type="text" class="form-control" name="datepicker" id="datepicker" placeholder="Enter date" required
                title="Date required">
            <select class="custom-select" name="golf_course" id="golf_course">
                {% for golf_course in golf_courses %}
                <option value="{{ golf_course.name }}">{{ golf_course.name }}</option>
                {% endfor %}
            </select>
            <input type="number" min="0" class="form-control" name="score" id="score" placeholder="Enter score" required>
            <div class="input-group-append">
                <button class="btn btn-primary" type="submit">Create</button>
            </div>
        </div>
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
        {% endif %}
    </form>
    <div class="table-container">
        <table class="table">
            <thead class="table-primary">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Date</th>
                    <th scope="col">Golf Course</th>
                    <th scope="col">Score</th>
                    <th scope="col">To par</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for count, score in scores %}
                <tr>
                    <form action="{% url 'web:delete_score' %}" method="post">
                        {% csrf_token %}
                        <td>{{ count }}</td>
                        <td>{{ score.date }}</td>
                        <td>{{ score.golf_course.name}}</td>
                        <td>{{ score.score }}</td>
                        {% if score.to_par < 0 %}
                        <td>{{ score.to_par }}</td>
                        {% else %}
                        <td>+{{ score.to_par }}</td>
                        {% endif %}
                        <td>
                            <button type="submit" class="close" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                                <input type="hidden" name="id" value="{{ score.id }}">
                            </button>
                        </td>
                    </form>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </div>
    {% endblock %}

golf_scores/templates/signin.html
{% extends "base.html" %} {% block content %}
<div class="centered-container container">
    <div class="sign-form card">
    <form class="form-submit" action="{% url 'accounts:signin' %}" method="post">
        {% csrf_token %}
        <h3>Sign In</h3>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="username" class="form-control" name="username" id="username" aria-describedby="username"
                placeholder="Enter username">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Password">
        </div>
        <p>Don't have an account? <a href="{% url 'accounts:signup' %}">Sign Up here<a /></p>
{% if error_message %}
<div class="alert alert-danger" role="alert">
    {{ error_message }}
</div>
{% endif %}
<button type="submit" class="btn btn-lg btn-primary btn-block">Sign In</button>
</form>
</div>
</div>
{% endblock %}

golf_scores/templates/signup.html
{% extends "base.html" %} {% block content %}
<div class="centered-container container">
    <div class="sign-form card">
    <form class="form-submit" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        <h3>Sign Up</h3>
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" class="form-control" name="username" id="username" placeholder="Enter username" />
        </div>
        <div class="form-group">
            <label for="email">E-mail address</label>
            <input type="email" class="form-control" name="email" id="email" aria-describedby="email"
                placeholder="Enter e-mail" />
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Password"
                pattern=".{6,}" required title="3 characters minimum" />
        </div>
        <div class="form-group">
            <label for="confirm_password">Confirm Password</label>
            <input type="password" class="form-control" name="confirm_password" id="confirm_password"
                placeholder="Confirm password" pattern=".{6,}" required title="6 characters minimum" />
        </div>
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{ error_message }}
        </div>
        {% endif %} {% if success_message %}
        <div class="alert alert-info" role="alert">
            {{ success_message }} <a href="{% url 'accounts:signin' %}">Sign In</a>
        </div>
        {% endif %}
        <button type="submit" class="btn btn-lg btn-primary btn-block">
            Sign Up
        </button>
    </form>
    </div>
</div>
{% endblock %}